<?php
    function googlePlaces_menu() {
      $items = array();
      $items['travel_options'] = array(
      'title' => 'Search Attractions',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('travel_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
      );
      $items['travel_results'] = array(
      'title' => 'Results',
      'page callback' => 'travel_search',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      );
      $items['save_results'] = array(
      'title' => 'My Results',
      'page callback' => 'save_view',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      );
      return $items;
    }

    function travel_form() {
      $form['attraction'] = array(
        '#title' => 'attraction',
        '#type' => 'textfield',
        '#description' => t('Please enter the type of attraction you are intereseted in'),
        '#required' => TRUE,
      );
      $form['city'] = array(
        '#title' => 'city',
        '#type' => 'textfield',
        '#description' => t('Please enter a city'),
      );
      $form['state'] = array(
        '#title' => 'state',
        '#type' => 'textfield',
        '#description' => t('Please enter a state'),
      );
      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Search',
      );
      return $form;
    }

    function checkbox_form() {
      $form['save'] = array(
        '#title' => '',
        '#type' => 'checkboxes',
        '#options' => array(
          0=>'save',
        ),
        '#description' => t('Check to save'),
      );
      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Save',
      );
      return $form;
    }

    function checkbox_form_submit($form, &$form_state) {
     $form_state['redirect'] = 'save_results';
    }

    function travel_form_submit($form, &$form_state) {
    $city = $form_state['values']['city'];
    $attraction = $form_state['values']['attraction'];
    $state = $form_state['values']['state'];
    $_SESSION['city'] = $city;
    $_SESSION['attraction'] = $attraction;
    $_SESSION['state'] = $state;

    $form_state['redirect'] = 'travel_results';
    }

    function save_view() {
      $output = $_SESSION['output'];
      var_dump($output);
      return $output;
    }

    function travel_search() {
      $output = '';
      $rating = '';
      $api_key = 'AIzaSyAOy8TYrUjMoRdW9-PIVi-50GnmGe_CDi8';
      $weather_key = '28eb4ab328f37f10';
      $attraction = $_SESSION['attraction'];
      $state = $_SESSION['state'];

      if(str_word_count($attraction) > 1) {
        $attraction = preg_replace('/\s+/', '', $attraction);
      }else {
        $attraction = $attraction;
      }

      $city = $_SESSION['city'];
      if(str_word_count($city) > 1) {
        $city = preg_replace('/\s+/', '', $city);
      }else {
        $city = $city;
      }

      $weather = 'http://api.wunderground.com/api/28eb4ab328f37f10/conditions/q/' . $state . '/' . $city . '.json';
      $result = file_get_contents($weather);
      $weather_array = json_decode($result, true);

      $local_time = $weather_array['current_observation']['local_time_rfc822'];
      $humidity = $weather_array['current_observation']['relative_humidity'];
      $temp_c = $weather_array['current_observation']['temp_c'];
      $temp_f = $weather_array['current_observation']['temp_f'];
      $current_condition = $weather_array['current_observation']['weather'];
      $last_updated = $weather_array['current_observation']['observation_time'];
      $city_state = $weather_array['current_observation']['display_location']['full'];

      $output = "<h2>The weather for " . $city_state . "</h2><br> as of " . $local_time . " is " . $current_condition . ". The temperature is " . $temp_f . " fahrenheit , and " . $temp_c . " celsius. This report was " . $last_updated . ".";

      $api_call ='https://maps.googleapis.com/maps/api/place/textsearch/json?query='.$attraction.'+in+'.$city.'&key='.$api_key;
      $result_string = file_get_contents($api_call);
      $result_array = json_decode($result_string, TRUE);

      if(empty($result_array['results'] === 'false')) {
        for ($i=0; $i < count($result_array['results']); $i++) {
        $address = $result_array['results'][$i]['formatted_address'];
        $name = $result_array['results'][$i]['name'];
        $place_id = $result_array['results'][$i]['place_id'];
          if(empty((string)$result_array['results'][$i]['rating']) === false) {
              $rating = (string)$result_array['results'][$i]['rating'];
          }else {
            $rating = "Sorry no rating";
          }
        $_SESSION['output'] = $name . $address . $rating;  
        $output = $output.<<<EOD
        <h2>$name</h2>
        <h4>Address: $address </h4>
        <h4>Rating: $rating </h4>
EOD;
         $checkbox_output = drupal_get_form('checkbox_form');
         $output .= drupal_render($checkbox_output);

        }
      }else {
        $output = "Sorry no results";
      }
      return $output;
    }
