<?php
function weather_menu() {
  $items = array();
  $items['weather'] = array(
    'title' => 'Check weather- weather condidions only available for the US currently',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('weather_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    );
    $items['weather_results'] = array(
    'title' => 'Results',
    'page callback' => 'weather_check',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    );
    return $items;
}

function weather_form() {
  $form['city'] = array(
    '#title' => 'city',
    '#type' => 'textfield',
    '#description' => t('Please enter a city'),
  );
  $form['state'] = array(
    '#title' => 'state',
    '#type' => 'textfield',
    '#element_validate' => array('element_validate_abbv'),
    '#description' => t('Please enter a state'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Check weather',
  );
  return $form;
}

function element_validate_abbv($element) {
  if(strlen($element['#value']) > 2) {
    var_dump($element);
         form_error($element, t('Please enter the two letter abbreviation for the state'));
     }
}

function weather_form_submit($form, &$form_state) {
  $city = $form_state['values']['city'];
  $state = $form_state['values']['state'];
  $_SESSION['city'] = $city;
  $_SESSION['state'] = $state;

  $form_state['redirect'] = 'weather_results';
}

function weather_check() {
  $city = $_SESSION['city'];
  $state = $_SESSION['state'];
  $weather_key = '28eb4ab328f37f10';

  if(str_word_count($city) > 1) {
    $city = str_replace(' ', '_', $city);
  }else {
    $city = $city;
  }

  $weather = 'http://api.wunderground.com/api/'.$weather_key.'/conditions/q/' . $state . '/' . $city . '.json';
  $result = file_get_contents($weather);
  $weather_array = json_decode($result, true);

  $local_time = $weather_array['current_observation']['local_time_rfc822'];
  $humidity = $weather_array['current_observation']['relative_humidity'];
  $temp_c = $weather_array['current_observation']['temp_c'];
  $temp_f = $weather_array['current_observation']['temp_f'];
  $current_condition = $weather_array['current_observation']['weather'];
  $last_updated = $weather_array['current_observation']['observation_time'];
  $city_state = $weather_array['current_observation']['display_location']['full'];

  $output = "<h2>The weather for " . $city_state . "</h2><br> as of " . $local_time . " is " . $current_condition . ". The temperature is " . $temp_f . " fahrenheit , and " . $temp_c . " celsius. This report was " . $last_updated . ".";

  return $output;
}
