<?php
    function packing_list_menu() {
      $items = array();

      $items['packing_list'] = array(
      'title' => 'Packing List',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('packing_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
      );
      $items['packing_list_results'] = array(
      'title' => 'Results',
      'page callback' => 'checked_list',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      );
      return $items;
    }

    function packing_form() {
      $toiletries_values = array(
         'shampoo' => t('shampoo'),
         'conditioner'=> t('conditioner'),
         'deodorant'=> t('deodorant'),
         'toothpaste' => t('toothpaste/toothbrush'),
      );
      $electronics_values = array(
        'camera' => t('camera'),
        'phone' => t('phone'),
        'tablet' => t('tablet'),
        'laptop'=> t('laptop'),
        'chargers' => t('chargers'),
        'adapator' => t('adapator'),
     );
     $clothes_values = array(
        'shirts' => t('shirts'),
        'pants/shorts' => t('pants/shorts'),
        'dresses' => t('dresses'),
        'underwear'=> t('underwear'),
        'shoes' => t('shoes'),
        'jacket/sweater' => t('jacket/sweater'),
     );
     $documents_values = array(
          'ID/passport' => t('ID/passport'),
          'copies of ID' => t('copies of ID'),
          'visa' => t('visa'),
     );
      $form['toiletries'] = array(
        '#title' => 'toiletries',
        '#type' => 'checkboxes',
        '#options' => $toiletries_values,
      );
      $form['electronics'] = array(
        '#title' => 'electronics',
        '#type' => 'checkboxes',
        '#options' => $electronics_values,
      );
        $form['clothes'] = array(
          '#title' => 'clothes',
          '#type' => 'checkboxes',
          '#options' => $clothes_values,
        );
      $form['documents'] = array(
        '#title' => 'documents',
        '#type' => 'checkboxes',
        '#options' => $documents_values,
      );
      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Save',
      );
      return $form;
    }

function packing_form_submit($form, &$form_state) {
    $toiletries = $form_state['values']['toiletries'];
    $clothes = $form_state['values']['clothes'];
    $documents = $form_state['values']['documents'];
    $electronics = $form_state['values']['electronics'];
    $_SESSION['toiletries'] = $toiletries;
    $_SESSION['clothes'] = $clothes;
    $_SESSION['documents'] = $documents;
    $_SESSION['electronics'] = $electronics;

    $form_state['redirect'] = 'packing_list_results';
  }

function checked_list() {
  $toiletries = $_SESSION['toiletries'];
  $clothes = $_SESSION['clothes'];
  $documents = $_SESSION['documents'];
  $electronics = $_SESSION['electronics'];
  $checked_output = <<<EOD
  <h2>Packed</h2>
  EOD;

  foreach ($toiletries as $item => $value) {
    $checked = array();
      if(gettype($value) === "string") {
        array_push($checked, $value);
      }
    for($i=0; $i< count($checked); $i++) {
      if($checked[$i] !== "null") {
          $output .= $checked[$i];
          var_dump($output);
      }
    }
  }
    return $output;
}
