<?php

    function skyscanner_menu() {
      $items = array();
      $items['flight_search'] = array(
          'title' => 'Flight search!',
          'page callback' => 'flight_search',
          'access callback' => TRUE,
          'type' => MENU_NORMAL_ITEM,
      );
      return $items;
    }

    function flight_search() {
      $url = 'http://partners.api.skyscanner.net/apiservices/pricing/v1.0/';
      $data = array('apiKey' => 'ep421720452997459494444425202337', 'country' => 'BR', 'currency' => 'BRL',
      'locale' => 'pt-BR', 'originplace' => 'SDU', 'destinationplace' => 'GRU', 'outbounddate' => '2017-09-23', 'inbounddate' => '2017-09-29');
      $httpdata = http_build_query($data);
      $ch = curl_init();
      curl_setopt($ch,CURLOPT_URL, $url);
      curl_setopt($ch, CURLOPT_POST, 1);
      curl_setopt($ch, CURLOPT_POSTFIELDS, $httpdata);
      curl_setopt($ch, CURLOPT_HEADER, 1);
      curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/x-www-form-urlencoded', 'Accept: application/json'));
      curl_setopt($ch, CURLOPT_VERBOSE, 1);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      $response = curl_exec($ch);
      curl_close($ch);
      var_dump($response);
    }
